export const ADD_STATE_SVG_FILE = 'ADD_STATE_SVG_FILE';
export const ADD_STATE_SVG_FILE_SUCCESS = 'ADD_STATE_SVG_FILE_SUCCESS';
export const ADD_STATE_SVG_FILE_FAILURE = 'ADD_STATE_SVG_FILE_FAILURE';

export const FETCH_LGA_BOUNDARIES = 'FETCH_LGA_BOUNDARIES';
export const FETCH_LGA_BOUNDARIES_SUCCESS = 'FETCH_LGA_BOUNDARIES_SUCCESS';
export const FETCH_LGA_BOUNDARIES_FAILURE = 'FETCH_LGA_BOUNDARIES_FAILURE';

export const UPDATE_LGA = 'UPDATE_LGA';
export const UPDATE_LGA_MAP_SUCCESS = 'UPDATE_LGA_SUCCESS';
export const UPDATE_LGA_MAP_FAILURE = 'UPDATE_LGA_FAILURE';
