version: "2"
checks:
  similar-code:
    config:
      threshold: 75
  identical-code:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 40

plugins:
  eslint:
    enabled: true
    channel: eslint-5

exclude_patterns:
  - "**/tests/"
  - "**/*.test.*"