sudo: required
language: node_js
node_js:
  - "9"
services:
  - docker
services:
    - docker

script:
    - echo "skipping tests"

after_deploy:
  - echo "done deploying"

before_deploy:
    #  build api
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker build -t mmdp_api -f ./Dockerfile-api .
    - docker images
    - docker tag mmdp_api $DOCKER_ID/mmdp_api
    - docker push $DOCKER_ID/mmdp_api
   #  build client
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker build -t mmdp_client -f ./Dockerfile-client .
    - docker images
    - docker tag mmdp_client $DOCKER_ID/mmdp_client
    - docker push $DOCKER_ID/mmdp_client
    #  build server
    
deploy:
    provider: elasticbeanstalk
    region: us-west-2
    app:  mmdp-cms
    env: MmdpCms-env-1
    bucket_name: elasticbeanstalk-us-west-2-817932213731
    bucket_path: mmdp_cms
    on:
       branch: ft-dev-environment-setup
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY

env:
  global:
    - NODE_ENV=development;DEV_MONGODB_URL=mongodb://54.202.70.86:27017/mmdp_db;mongo=mongodb://54.202.70.86:27017/mmdp_db;key=$AWS_ACCESS_KEY;secret=$AWS_SECRET_KEY;bucket=mmdp-img-assets;region=us-east-2

#   matrix:
#     - NODE_ENV=development
#     - NODE_ENV=production