sudo: required
language: node_js
node_js:
  - "9"
services:
  - docker

script:
  - echo "skipping tests"

jobs:
  include:
    - stage: build api
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker build -t mmdp_api -f ./Dockerfile-api .
        - docker images
        - docker tag mmdp_api $DOCKER_ID/mmdp_api
        - docker push $DOCKER_ID/mmdp_api
    - stage: build client
      script:
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
          - docker build -t mmdp_client -f ./Dockerfile-client .
          - docker images
          - docker tag mmdp_client $DOCKER_ID/mmdp_client
          - docker push $DOCKER_ID/mmdp_client

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app:  mmdp-cms
  env:  mmdp-cms-app
  bucket_name: elasticbeanstalk-us-west-2-817932213731
  bucket_path: mmdp_cms
  on:
    branch: ft-fix-remote-deployment
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
