sudo: required
services:
    - docker

script:
    - echo "skipping tests"

after_deploy:
  - echo "done deploying"

before_deploy:
    #  build api
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker build -t mmdp_api -f ./Dockerfile-api .
    - docker images
    - docker tag mmdp_api $DOCKER_ID/mmdp_api
    - docker push $DOCKER_ID/mmdp_api
   #  build client
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker build -t mmdp_client -f ./Dockerfile-client .
    - docker images
    - docker tag mmdp_client $DOCKER_ID/mmdp_client
    - docker push $DOCKER_ID/mmdp_client
    #  build server
    
deploy:
    provider: elasticbeanstalk
    region: us-west-2
    app:  mmdp-cms
    env: MmdpCms-env-1
    bucket_name: elasticbeanstalk-us-west-2-817932213731
    bucket_path: mmdp_cms
    on:
       branch: ft-dev-environment-setup
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY

env:
  global:
    - DEV_MONGODB_URL=mongodb://54.202.70.86:27017/mmdp_db
    - MONGODB_URL=mongodb://54.202.70.86:27017/mmdp_db
    - S3_KEY=$AWS_ACCESS_KEY
    - S3_SECRET=$AWS_SECRET_KEY
    - S3_BUCKET=mmdp-img-assets
    - S3_REGION=us-east-2

  matrix:
    - NODE_ENV=development
    - NODE_ENV=production