FROM node:alpine AS builder

WORKDIR "/mmdp"

COPY ./package.json ./

COPY ./ ./

RUN yarn install

CMD ["yarn", "run", "build:client"]


FROM nginx
COPY --from=builder /mmdp /usr/share/nginx/html/

COPY ./default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
