version: "3"

services:
  mongo:
    build:
      context: ./
      dockerfile: Dockerfile-db
    ports:
      - "27017:27017"


  api:
    build:
      context: ./
      dockerfile: Dockerfile-api
    volumes:
      - "./server:$HOME/mmdp/"
      - "./node_modules:$HOME/mmdp/node_modules"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo

  client:
    build:
      context: ./
      dockerfile: Dockerfile-client
    volumes:
      - "./client:$HOME/mmdp/"
      - "/mmdp/node_modules"
    ports:
      - "1234:1234"
    links:
      - api

  nginx:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    ports:
      - "8080:80"
