FROM node:alpine

WORKDIR $HOME/mmdp/

ARG NODE_ENV=development
ENV NODE_ENV=$NODE_ENV

ARG JWT_SECRET=secret
ENV JWT_SECRET=$JWT_SECRET

ARG COOKIE_SECRET=ffffffffgggggggggg
ENV COOKIE_SECRET=COOKIE_SECRET

ARG MONGODB_URL=mongodb://172.22.0.2/mmdp_data
ENV MONGODB_URL=$MONGODB_URL

ARG DEV_MONGODB_URL=mongodb://172.22.0.2/mmdp_data
ENV DEV_MONGODB_URL=$DEV_MONGODB_URL

COPY ./package.json ./

COPY ./ ./

RUN yarn install

EXPOSE 3000
CMD ["yarn", "run", "run:server"]
