FROM node:alpine

WORKDIR $HOME/mmdp/

COPY ./package.json ./

RUN apk --no-cache --virtual build-dependencies add \
    python \
    make \
    g++ \
    && yarn install \
    && apk del build-dependencies


COPY ./ ./


EXPOSE 1234
CMD ["yarn", "run", "client:dev"]
