FROM node:alpine

WORKDIR $HOME/mmdp/

RUN apk --no-cache --virtual build-dependencies add \
    python \
    make \
    g++ \
    && yarn install \
    && apk del build-dependencies

COPY ./package.json ./

COPY ./ ./

EXPOSE 3000 

CMD ["yarn", "run", "start:server"]
