version: "3"

services:
  mongo:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile-db
    ports:
      - "27017:27017"
    networks:
      - backend


  api:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile-api
    volumes:
      - "/mmdp/node_modules"
      - "./server:$HOME/mmdp/"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - backend
    env_file:
      - ./.env

  client:
    restart: always
    links:
      - mongo

  client:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile-client
    volumes:
      - "./client:$HOME/mmdp/"
      - "/mmdp/node_modules"
    ports:
      - "1234:1234"
    links:
      - api
    depends_on:
      - api
    networks:
      - backend
    links:
      - api
    depends_on:
      - api
    networks:
      - backend

  nginx:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    ports:
      - "8080:80"
    networks:
      - backend
    depends_on:
      - client
networks:
  backend:
    driver: bridge
