version: "3"

services:
  mongo:
    build:
      context: ./
      dockerfile: Dockerfile-db
    ports:
      - "27017:27017"


  api:
    build:
      context: ./
      dockerfile: Dockerfile-api
    volumes:
      - "/mmdp/node_modules"
      - "./server:$HOME/mmdp/"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      
  client: 
    build:
      context: ./
      dockerfile: Dockerfile-client
    volumes:
      - "/mmdp/node_modules"
      - "./client:$HOME/mmdp/"
    ports:
      - "1234:1234"
    

  nginx:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    ports:
      - "8080:80"

  
  
  