version: '3'

services:
  mongo-server:
    image: mongo:3.4.19-jessie
    ports:
      - "27017:27017"
  web-app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "1234:1234"
      - "3000:3000" 
    volumes:
      - /mmdp/node_modules
      - .:/mmdp

  