FROM python:3.6-alpine as Builder

WORKDIR $HOME/mmdp/

RUN apk  add --update alpine-sdk  && \
    apk add curl
 
RUN npm install -g yarn


FROM node:alpine

WORKDIR $HOME/mmdp/

COPY ./package.json ./

COPY ./ ./

RUN yarn install

EXPOSE 3000 

CMD ["yarn", "run", "start:server"]
