export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTERING_USER = "REGISTERING_USER";
export const FETCHING_USERS_SUCCESS = "FETCHING_USERS_SUCCESS";
export const FETCHING = "FETCHING";
export const FETCHING_STARTED = "FETCHING_STARTED";
export const FETCHING_USERS_ERROR = "FETCHING_USERS_ERROR";
