branch-defaults:
  develop:
    environment: MmdpCms-env-1
  ft-fix-remote-deployment:
    environment: MmdpCms-env-1
environment-defaults:
  MmdpCms-env-1:
    branch: null
    repository: null
global:
  application_name: mmdp-cms
<<<<<<< HEAD
  default_ec2_keyname: mmdpCms
  default_platform: Docker 18.06.1-ce
=======
  default_ec2_keyname: mmdp-dev-key
  default_platform: Multi-container Docker 18.06.1-ce (Generic)
>>>>>>> feat(fix-remote-deployment): Fix deployment issues
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
