export const CREATE_PILLAR_ONE = 'CREATE_PILLAR_ONE';
export const GET_PILLAR_ONE = 'GET_PILLAR_ONE';
export const UPDATE_PILLAR_ONE = 'UPDATE_PILLAR_ONE';
export const PILLAR_MESSAGE_SUCCESS_ONE = 'PILLAR_MESSAGE_SUCCESS_ONE';
export const PILLAR_MESSAGE_FAILURE_ONE = 'PILLAR_MESSAGE_FAILURE_ONE';
export const PILLAR_MESSAGE_LOADING_ONE = 'PILLAR_MESSAGE_LOADING_ONE';

export const CREATE_PILLAR_TWO = 'CREATE_PILLAR_TWO';
export const GET_PILLAR_TWO = 'GET_PILLAR_TWO';
export const UPDATE_PILLAR_TWO = 'UPDATE_PILLAR_TWO';
export const PILLAR_MESSAGE_SUCCESS_TWO = 'PILLAR_MESSAGE_SUCCESS_TWO';
export const PILLAR_MESSAGE_FAILURE_TWO = 'PILLAR_MESSAGE_FAILURE_TWO';
export const PILLAR_MESSAGE_LOADING_TWO = 'PILLAR_MESSAGE_LOADING_TWO';

export const CREATE_PILLAR_THREE = 'CREATE_PILLAR_THREE';
export const GET_PILLAR_THREE = 'GET_PILLAR_THREE';
export const UPDATE_PILLAR_THREE = 'UPDATE_PILLAR_THREE';
export const PILLAR_MESSAGE_SUCCESS_THREE = 'PILLAR_MESSAGE_SUCCESS_THREE';
export const PILLAR_MESSAGE_FAILURE_THREE = 'PILLAR_MESSAGE_FAILURE_THREE';
export const PILLAR_MESSAGE_LOADING_THREE = 'PILLAR_MESSAGE_LOADING_THREE';

export const CREATE_PILLAR_FOUR = 'CREATE_PILLAR_FOUR';
export const GET_PILLAR_FOUR = 'GET_PILLAR_FOUR';
export const UPDATE_PILLAR_FOUR = 'UPDATE_PILLAR_FOUR';
export const PILLAR_MESSAGE_SUCCESS_FOUR = 'PILLAR_MESSAGE_SUCCESS_FOUR';
export const PILLAR_MESSAGE_FAILURE_FOUR = 'PILLAR_MESSAGE_FAILURE_FOUR';
export const PILLAR_MESSAGE_LOADING_FOUR = 'PILLAR_MESSAGE_LOADING_FOUR';
