export const CREATE_ABOUT_MMDP_REQUEST = 'CREATE_ABOUT_MMDP_REQUEST';
export const GET_ABOUT_MMDP_REQUEST = 'GET_ABOUT_MMDP_REQUEST';
export const UPDATE_ABOUT_MMDP_REQUEST = 'UPDATE_ABOUT_MMDP_REQUEST';
export const ABOUT_MMDP_SUCCESS = 'ABOUT_MMDP_SUCCESS';
export const ABOUT_MMDP_FAILURE = 'ABOUT_MMDP_FAILURE';
export const ABOUT_MMDP_LOADING = 'ABOUT_MMDP_LOADING';
