export const CREATE_GOVERNOR_MESSAGE_REQUEST = 'CREATE_GOVERNOR_MESSAGE_REQUEST';
export const GET_GOVERNOR_MESSAGE_REQUEST = 'GET_GOVERNOR_MESSAGE_REQUEST';
export const UPDATE_GOVERNOR_MESSAGE_REQUEST = 'UPDATE_GOVERNOR_MESSAGE_REQUEST';
export const GOVERNOR_MESSAGE_SUCCESS = 'GOVERNOR_MESSAGE_SUCCESS';
export const GOVERNOR_MESSAGE_FAILURE = 'GOVERNOR_MESSAGE_FAILURE';
export const GOVERNOR_MESSAGE_LOADING = 'GOVERNOR_MESSAGE_LOADING';
