export const CREATE_ABOUT_MMDP_REQUEST = 'CREATE_ABOUT_MMDP_REQUEST';
export const GET_ABOUT_MMDP_REQUEST = 'GET_ABOUT_MMDP_REQUEST';
export const UPDATE_ABOUT_MMDP_REQUEST = 'UPDATE_ABOUT_MMDP_REQUEST';
export const ABOUT_MMDP_SUCCESS = 'ABOUT_MMDP_SUCCESS';
export const ABOUT_MMDP_FAILURE = 'ABOUT_MMDP_FAILURE';
export const ABOUT_MMDP_LOADING = 'ABOUT_MMDP_LOADING';

export const CREATE_COORDINATION_REQUEST = 'CREATE_COORDINATION_REQUEST';
export const GET_COORDINATION_REQUEST = 'GET_COORDINATION_REQUEST';
export const UPDATE_COORDINATION_REQUEST = 'UPDATE_COORDINATION_REQUEST';
export const COORDINATION_SUCCESS = 'COORDINATION_SUCCESS';
export const COORDINATION_FAILURE = 'COORDINATION_FAILURE';
export const COORDINATION_LOADING = 'COORDINATION_LOADING';

export const CREATE_GOVERNOR_MESSAGE_REQUEST =
  'CREATE_GOVERNOR_MESSAGE_REQUEST';
export const GET_GOVERNOR_MESSAGE_REQUEST = 'GET_GOVERNOR_MESSAGE_REQUEST';
export const UPDATE_GOVERNOR_MESSAGE_REQUEST =
  'UPDATE_GOVERNOR_MESSAGE_REQUEST';
export const GOVERNOR_MESSAGE_SUCCESS = 'GOVERNOR_MESSAGE_SUCCESS';
export const GOVERNOR_MESSAGE_FAILURE = 'GOVERNOR_MESSAGE_FAILURE';
export const GOVERNOR_MESSAGE_LOADING = 'GOVERNOR_MESSAGE_LOADING';
