export const ADD_TEMP_AMOUNT = 'ADD_TEMP_AMOUNT';
export const EDIT_AMOUNT = 'EDIT_AMOUNT';

export const ADD_AMOUNT = 'ADD_AMOUNT';
export const ADD_AMOUNT_SUCCESS = 'ADD_AMOUNT_SUCCESS';
export const ADD_AMOUNT_FAILURE = 'ADD_AMOUNT_FAILURE';

export const FETCH_AMOUNT = 'FETCH_AMOUNT';
export const FETCH_AMOUNT_SUCCESS = 'FETCH_AMOUNT_SUCCESS';
export const FETCH_AMOUNT_FAILURE = 'FETCH_AMOUNT_FAILURE';

export const DELETE_AMOUNT = 'DELETE_AMOUNT';
export const DELETE_AMOUNT_SUCCESS = 'DELETE_AMOUNT_SUCCESS';
export const DELETE_AMOUNT_FAILURE = 'DELETE_AMOUNT_FAILURE';
