export const ADD_TEMPORARY_COMMUNITY = 'ADD_TEMPORARY_COMMUNITY';
export const EDIT_COMMUNITY = 'EDIT_COMMUNITY';

export const ADD_COMMUNITIES = 'ADD_COMMUNITIES';
export const ADD_COMMUNITIES_SUCCESS = 'ADD_COMMUNITIES_SUCCESS';
export const ADD_COMMUNITIES_FAILURE = 'ADD_COMMUNITIES_FAILURE';

export const FETCH_COMMUNITIES = 'FETCH_COMMUNITIES';
export const FETCH_COMMUNITIES_SUCCESS = 'FETCH_COMMUNITIES_SUCCESS';
export const FETCH_COMMUNITIES_FAILURE = 'FETCH_COMMUNITIES_FAILURE';

export const DELETE_COMMUNITY = 'DELETE_COMMUNITY';
export const DELETE_COMMUNITY_SUCCESS = 'DELETE_COMMUNITY_SUCCESS';
export const DELETE_COMMUNITY_FAILURE = 'DELETE_COMMUNITY_FAILURE';
