export const GET_COUNTRY_DROPDOWN_REQUEST = 'GET_COUNTRY_DROPDOWN_REQUEST';
export const GET_COUNTRY_DROPDOWN_SUCCESS = 'GET_COUNTRY_DROPDOWN_SUCCESS';
export const GET_COUNTRY_DROPDOWN_FAILURE = 'GET_COUNTRY_DROPDOWN_FAILURE';
export const UPDATE_COUNTRY_DROPDOWN_REQUEST = 'UPDATE_COUNTRY_DROPDOWN';
export const UPDATE_COUNTRY_DROPDOWN_SUCCESS =
  'UPDATE_COUNTRY_DROPDOWN_SUCCESS';
export const UPDATE_COUNTRY_DROPDOWN_FAILURE =
  'UPDATE_COUNTRY_DROPDOWN_FAILURE';
export const DELETE_USER_COUNTRY_DROPDOWN = 'DELETE_USER_COUNTRY_DROPDOWN';
export const DELETE_USER_COUNTRY_DROPDOWN_SUCCESS =
  'DELETE_USER_COUNTRY_DROPDOWN_SUCCESS';
export const DELETE_USER_COUNTRY_DROPDOWN_FAILURE =
  'DELETE_USER_COUNTRY_DROPDOWN_FAILURE';
