export const ADD_TEMP_FOCUS_AREA = 'ADD_TEMP_FOCUS_AREA';
export const EDIT_FOCUS_AREA = 'EDIT_FOCUS_AREA';

export const ADD_FOCUS_AREA = 'ADD_FOCUS_AREA';
export const ADD_FOCUS_AREA_SUCCESS = 'ADD_FOCUS_AREA_SUCCESS';
export const ADD_FOCUS_AREA_FAILURE = 'ADD_FOCUS_AREA_FAILURE';

export const FETCH_FOCUS_AREA = 'FETCH_FOCUS_AREA';
export const FETCH_FOCUS_AREA_SUCCESS = 'FETCH_FOCUS_AREA_SUCCESS';
export const FETCH_FOCUS_AREA_FAILURE = 'FETCH_FOCUS_AREA_FAILURE';

export const DELETE_FOCUS_AREA = 'DELETE_FOCUS_AREA';
export const DELETE_FOCUS_AREA_SUCCESS = 'DELETE_FOCUS_AREA_SUCCESS';
export const DELETE_FOCUS_AREA_FAILURE = 'DELETE_FOCUS_AREA_FAILURE';
