export const ADD_TEMP_FREQUENCY = 'ADD_TEMP_FREQUENCY';
export const EDIT_FREQUENCY = 'EDIT_FREQUENCY';

export const ADD_FREQUENCY = 'ADD_FREQUENCY';
export const ADD_FREQUENCY_SUCCESS = 'ADD_FREQUENCY_SUCCESS';
export const ADD_FREQUENCY_FAILURE = 'ADD_FREQUENCY_FAILURE';

export const FETCH_FREQUENCY = 'FETCH_FREQUENCY';
export const FETCH_FREQUENCY_SUCCESS = 'FETCH_FREQUENCY_SUCCESS';
export const FETCH_FREQUENCY_FAILURE = 'FETCH_FREQUENCY_FAILURE';

export const DELETE_FREQUENCY = 'DELETE_FREQUENCY';
export const DELETE_FREQUENCY_SUCCESS = 'DELETE_FREQUENCY_SUCCESS';
export const DELETE_FREQUENCY_FAILURE = 'DELETE_FREQUENCY_FAILURE';
