export const ADD_TEMP_FUNDING = 'ADD_TEMP_FUNDING';
export const EDIT_FUNDING = 'EDIT_FUNDING';

export const ADD_FUNDING = 'ADD_FUNDING';
export const ADD_FUNDING_SUCCESS = 'ADD_FUNDING_SUCCESS';
export const ADD_FUNDING_FAILURE = 'ADD_FUNDING_FAILURE';

export const FETCH_FUNDING = 'FETCH_FUNDING';
export const FETCH_FUNDING_SUCCESS = 'FETCH_FUNDING_SUCCESS';
export const FETCH_FUNDING_FAILURE = 'FETCH_FUNDING_FAILURE';

export const DELETE_FUNDING = 'DELETE_FUNDING';
export const DELETE_FUNDING_SUCCESS = 'DELETE_FUNDING_SUCCESS';
export const DELETE_FUNDING_FAILURE = 'DELETE_FUNDING_FAILURE';
