export const ADD_TEMPORARY_IMPACT_TYPE = 'ADD_TEMPORARY_IMPACT_TYPE';
export const EDIT_IMPACT_TYPE = 'EDIT_IMPACT_TYPE';

export const ADD_IMPACT_TYPES = 'ADD_IMPACT_TYPES';
export const ADD_IMPACT_TYPES_SUCCESS = 'ADD_IMPACT_TYPES_SUCCESS';
export const ADD_IMPACT_TYPES_FAILURE = 'ADD_IMPACT_TYPES_FAILURE';

export const FETCH_IMPACT_TYPES = 'FETCH_IMPACT_TYPES';
export const FETCH_IMPACT_TYPES_SUCCESS = 'FETCH_IMPACT_TYPES_SUCCESS';
export const FETCH_IMPACT_TYPES_FAILURE = 'FETCH_IMPACT_TYPES_FAILURE';

export const DELETE_IMPACT_TYPE = 'DELETE_IMPACT_TYPE';
export const DELETE_IMPACT_TYPE_SUCCESS = 'DELETE_IMPACT_TYPE_SUCCESS';
export const DELETE_IMPACT_TYPE_FAILURE = 'DELETE_IMPACT_TYPE_FAILURE';
