export const ADD_LGA_REQUEST = 'ADD_LGA';
export const ADD_LGA_SUCCESS = 'ADD_LGA_SUCCESS';
export const ADD_LGA_FAILURE = 'ADD_LGA_FAILURE';

export const UPDATE_LGA_REQUEST = 'UPDATE_LGA';
export const UPDATE_LGA_SUCCESS = 'UPDATE_LGA_SUCCESS';
export const UPDATE_LGA_FAILURE = 'UPDATE_LGA_FAILURE';

export const GET_LGA_REQUEST = 'GET_LGA';
export const GET_LGA_SUCCESS = 'GET_LGA_SUCCESS';
export const GET_LGA_FAILURE = 'GET_LGA_FAILURE';

export const DELETE_LGA_REQUEST = 'DELETE_LGA';
export const DELETE_LGA_SUCCESS = 'DELETE_LGA_SUCCESS';
export const DELETE_LGA_FAILURE = 'DELETE_LGA_FAILURE';
