export const ADD_ORGANIZATION_TYPE_REQUEST = 'ADD_ORGANIZATION_TYPE';
export const ADD_ORGANIZATION_TYPE_SUCCESS = 'ADD_ORGANIZATION_TYPE_SUCCESS';
export const ADD_ORGANIZATION_TYPE_FAILURE = 'ADD_ORGANIZATION_TYPE_FAILURE';

export const UPDATE_ORGANIZATION_TYPE_REQUEST = 'UPDATE_ORGANIZATION_TYPE';
export const UPDATE_ORGANIZATION_TYPE_SUCCESS =
  'UPDATE_ORGANIZATION_TYPE_SUCCESS';
export const UPDATE_ORGANIZATION_TYPE_FAILURE =
  'UPDATE_ORGANIZATION_TYPE_FAILURE';

export const GET_ORGANIZATION_TYPE_REQUEST = 'GET_ORGANIZATION_TYPE';
export const GET_ORGANIZATION_TYPE_SUCCESS = 'GET_ORGANIZATION_TYPE_SUCCESS';
export const GET_ORGANIZATION_TYPE_FAILURE = 'GET_ORGANIZATION_TYPE_FAILURE';

export const DELETE_ORGANIZATION_TYPE_REQUEST = 'DELETE_ORGANIZATION_TYPE';
export const DELETE_ORGANIZATION_TYPE_SUCCESS =
  'DELETE_ORGANIZATION_TYPE_SUCCESS';
export const DELETE_ORGANIZATION_TYPE_FAILURE =
  'DELETE_ORGANIZATION_TYPE_FAILURE';
