export const ADD_TEMPORARY_PARTNERSHIP_TYPE = 'ADD_TEMPORARY_PARTNERSHIP_TYPE';
export const EDIT_PARTNERSHIP_TYPE = 'EDIT_PARTNERSHIP_TYPE';

export const ADD_PARTNERSHIP_TYPES = 'ADD_PARTNERSHIP_TYPES';
export const ADD_PARTNERSHIP_TYPES_SUCCESS = 'ADD_PARTNERSHIP_TYPES_SUCCESS';
export const ADD_PARTNERSHIP_TYPES_FAILURE = 'ADD_PARTNERSHIP_TYPES_FAILURE';

export const FETCH_PARTNERSHIP_TYPES = 'FETCH_PARTNERSHIP_TYPES';
export const FETCH_PARTNERSHIP_TYPES_SUCCESS =
  'FETCH_PARTNERSHIP_TYPES_SUCCESS';
export const FETCH_PARTNERSHIP_TYPES_FAILURE =
  'FETCH_PARTNERSHIP_TYPES_FAILURE';

export const DELETE_PARTNERSHIP_TYPE = 'DELETE_PARTNERSHIP_TYPE';
export const DELETE_PARTNERSHIP_TYPE_SUCCESS =
  'DELETE_PARTNERSHIP_TYPE_SUCCESS';
export const DELETE_PARTNERSHIP_TYPE_FAILURE =
  'DELETE_PARTNERSHIP_TYPE_FAILURE';
