export const ADD_TEMPORARY_STATE = 'ADD_TEMPORARY_STATE';
export const EDIT_STATE = 'EDIT_STATE';

export const ADD_STATES = 'ADD_STATES';
export const ADD_STATES_SUCCESS = 'ADD_STATES_SUCCESS';
export const ADD_STATES_FAILURE = 'ADD_STATES_FAILURE';

export const FETCH_STATES = 'FETCH_STATES';
export const FETCH_STATES_SUCCESS = 'FETCH_STATES_SUCCESS';
export const FETCH_STATES_FAILURE = 'FETCH_STATES_FAILURE';

export const DELETE_STATE = 'DELETE_STATE';
export const DELETE_STATE_SUCCESS = 'DELETE_STATE_SUCCESS';
export const DELETE_STATE_FAILURE = 'DELETE_STATE_FAILURE';
