export const ADD_TEMPORARY_ = 'ADD_TEMPORARY_SUBTHEME';
export const EDIT_SUBTHEME = 'EDIT_SUBTHEME';

export const ADD_SUBTHEMES = 'ADD_SUBTHEMES';
export const ADD_SUBTHEMES_SUCCESS = 'ADD_SUBTHEMES_SUCCESS';
export const ADD_SUBTHEMES_FAILURE = 'ADD_SUBTHEMES_FAILURE';

export const FETCH_SUBTHEMES = 'FETCH_SUBTHEMES';
export const FETCH_SUBTHEMES_SUCCESS = 'FETCH_SUBTHEMES_SUCCESS';
export const FETCH_SUBTHEMES_FAILURE = 'FETCH_SUBTHEMES_FAILURE';

export const DELETE_SUBTHEME = ' DELETE_SUBTHEME ';
export const DELETE_SUBTHEME_SUCCESS = ' DELETE_SUBTHEME_SUCCESS';
export const DELETE_SUBTHEME_FAILURE = ' DELETE_SUBTHEME_FAILURE';
