export const FETCH_TARGET_AUDIENCES = 'FETCH_TARGET_AUDIENCES';
export const FETCHING_TARGET_AUDIENCES = 'FETCHING_TARGET_AUDIENCES';

export const CREATE_TARGET_AUDIENCES = 'CREATE_TARGET_AUDIENCES';
export const CREATING_TARGET_AUDIENCES = 'CREATING_TARGET_AUDIENCES';
export const TARGET_AUDIENCES_CREATED_SUCCESS =
  'TARGET_AUDIENCES_CREATED_SUCCESS';
export const CREATE_TARGET_AUDIENCES_FAILURE =
  'CREATE_TARGET_AUDIENCES_FAILURE';

export const UPDATE_TARGET_AUDIENCES = 'UPDATE_TARGET_AUDIENCES';
export const UPDATE_TARGET_AUDIENCES_FAILURE =
  'UPDATE_TARGET_AUDIENCES_FAILURE';
export const DELETE_TARGET_AUDIENCE = 'DELETE_TARGET_AUDIENCE';
