export const ADD_TEMPORARY_WARD = 'ADD_TEMPORARY_WARD';
export const EDIT_WARD = 'EDIT_WARD';

export const ADD_WARDS = 'ADD_WARDS';
export const ADD_WARDS_SUCCESS = 'ADD_WARDS_SUCCESS';
export const ADD_WARDS_FAILURE = 'ADD_WARDS_FAILURE';

export const FETCH_WARDS = 'FETCH_WARDS';
export const FETCH_WARDS_SUCCESS = 'FETCH_WARDS_SUCCESS';
export const FETCH_WARDS_FAILURE = 'FETCH_WARDS_FAILURE';

export const DELETE_WARD = ' DELETE_WARD ';
export const DELETE_WARD_SUCCESS = ' DELETE_WARD_SUCCESS';
export const DELETE_WARD_FAILURE = ' DELETE_WARD_FAILURE';
