export const DELETE_DROPDOWNS = ' DELETE_DROPDOWNS ';
export const DELETE_DROPDOWNS_SUCCESS = ' DELETE_DROPDOWNS_SUCCESS';
export const DELETE_DROPDOWNS_FAILURE = ' DELETE_DROPDOWNS_FAILURE';

export const FETCH_DROPDOWNS = 'FETCH_DROPDOWNS';
export const FETCH_DROPDOWNS_SUCCESS = 'FETCH_DROPDOWNS_SUCCESS';
export const FETCH_DROPDOWNS_FAILURE = 'FETCH_DROPDOWNS_FAILURE';
