export const GET_ALL_NIGERIAN_STATES = 'GET_ALL_NIGERIAN_STATES';
export const GET_ALL_NIGERIAN_LGAS = 'GET_ALL_NIGERIAN_LGAS';

export const GET_ALL_NIGERIAN_STATES_SUCCESS =
  'GET_ALL_NIGERIAN_STATES_SUCCESS';
export const GET_ALL_NIGERIAN_STATES_FAILURE =
  'GET_ALL_NIGERIAN_STATES_FAILURE';

export const GET_ALL_NIGERIAN_LGAS_SUCCESS = 'GET_ALL_NIGERIAN_LGAS_SUCCESS';
export const GET_ALL_NIGERIAN_LGAS_FAILURE = 'GET_ALL_NIGERIAN_LGAS_FAILURE';

export const FETCH_STAKEHOLDERS = 'FETCH_STAKEHOLDERS';
export const FETCH_STAKEHOLDERS_SUCCESS = 'FETCH_STAKEHOLDERS_SUCCESS';
export const FETCH_STAKEHOLDERS_FAILURE = 'FETCH_STAKEHOLDERS_FAILURE';

export const FILTER_SEARCH_RESULTS = 'FILTER_SEARCH_RESULTS';
export const FILTER_SEARCH_RESULTS_UPDATE = 'FILTER_SEARCH_RESULTS_UPDATE';
