export const FETCH_GROUPS = 'FETCH_GROUPS';
export const FETCH_GROUP = 'FETCH_GROUP';
export const FETCHING_GROUPS = 'FETCHING_GROUPS';

export const CREATE_GROUP = 'CREATE_GROUP';
export const CREATING_GROUP = 'CREATING_GROUP';
export const GROUP_CREATED_SUCCESS = 'GROUP_CREATED_SUCCESS';
export const CREATE_GROUP_FAILURE = 'CREATE_GROUP_FAILURE';

export const UPDATE_GROUP = 'UPDATE_GROUP';
export const EDIT_GROUP = 'EDIT_GROUP';
export const CLEAR_GROUP_ERRORS = 'CLEAR_GROUP_ERRORS';

export const SET_GROUP = 'SET_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const CLEAR_GROUP = 'CLEAR_GROUP';
export const TOGGLE_DELETE_GROUP = 'TOGGLE_DELETE_GROUP';

export const ADD_GROUP_ITEM = 'ADD_GROUP_ITEM';
export const ADD_ALL_GROUP_ITEM = 'ADD_ALL_GROUP_ITEM';
export const REMOVE_ALL_GROUP_ITEM = 'REMOVE_ALL_GROUP_ITEM';

export const SELECT_A_GROUP = 'SELECT_A_GROUP';
export const SELECT_ALL_GROUPS = 'SELECT_ALL_GROUPS';
export const UNSELECT_ALL_GROUPS = 'UNSELECT_ALL_GROUPS';
export const TOGGLE_SELECT_GROUPS = 'TOGGLE_SELECT_GROUPS';
