export const FETCH_STAFF_STRENGTHS = 'FETCH_STAFF_STRENGTHS';
export const FETCHING_STAFF_STRENGTHS = 'FETCHING_STAFF_STRENGTHS';

export const CREATE_STAFF_STRENGTHS = 'CREATE_STAFF_STRENGTHS';
export const CREATING_STAFF_STRENGTHS = 'CREATING_STAFF_STRENGTHS';
export const STAFF_STRENGTHS_CREATED_SUCCESS =
  'STAFF_STRENGTHS_CREATED_SUCCESS';
export const CREATE_STAFF_STRENGTHS_FAILURE = 'CREATE_STAFF_STRENGTHS_FAILURE';

export const UPDATE_STAFF_STRENGTHS = 'UPDATE_STAFF_STRENGTHS';
export const EDIT_STAFF_STRENGTH = 'EDIT_STAFF_STRENGTH';
export const DELETE_STAFF_STRENGTH = 'DELETE_STAFF_STRENGTH';
export const CLEAR_STAFF_STRENGTHS = 'CLEAR_STAFF_STRENGTHS';
