export const ADD_STAKEHOLDER_REQUEST = 'ADD_STAKEHOLDER_REQUEST';
export const ADD_STAKEHOLDER_SUCCESS = 'ADD_STAKEHOLDER_SUCCESS';
export const ADD_STAKEHOLDER_FAILURE = 'ADD_STAKEHOLDER_FAILURE';

export const REMOVE_STAKEHOLDER_REQUEST = 'REMOVE_STAKEHOLDER_REQUEST';
export const REMOVE_STAKEHOLDER_SUCCESS = 'REMOVE_STAKEHOLDER_SUCCESS';
export const REMOVE_STAKEHOLDER_FAILURE = 'REMOVE_STAKEHOLDER_FAILURE';

export const EDIT_STAKEHOLDER_REQUEST = 'EDIT_STAKEHOLDER_REQUEST';
export const EDIT_STAKEHOLDER_SUCCESS = 'EDIT_STAKEHOLDER_SUCCESS';
export const EDIT_STAKEHOLDER_FAILURE = 'EDIT_STAKEHOLDER_FAILURE';
